version: "3"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
  redis:
    image: redis

    # TODO: pass name for webpage from docker compose

    # TODO: (big) qr generation
    # TODO: (big) make also work from adding a prefix