version: "3"

services:
  web:
    build:
      context: .
      args:
        - DOMAIN='shorter.fit'
    ports:
      - "80:8000"
  redis:
    image: redis
    # TODO: setup redis password
    # TODO: save db on server not in container
